version: 1.0.{build}
install:
- cmd: >-
    git clone https://%GITLABUSR%:%GITLABPASS%@gitlab.com/ClxS/Tool.git C:\projects\stardew-farmhand\WorkingDirectory\tmp

    move C:\projects\stardew-farmhand\WorkingDirectory\tmp\*.* C:\projects\stardew-farmhand\WorkingDirectory
before_build:
- cmd: nuget restore
build:
  verbosity: minimal